### ISSUE TITLE
How to handle sliders?

### ISSUE THREAD

**Issue by verbeeksteven** [imageboss/imageboss-web#1]
Hello,

I am wondering what you think about how to handle sliders? On page load sliders have not initialized so images within sliders have no set `clientWidth` and you cannot reliably set a `data-imageboss-width` as it is variable depending on screensize (unless something like vw or % would work).

Is there some way to wait until slider is initialized to do replacement or something?

**Comment by igorescobar** [comment]
@verbeeksteven 
What you could do here is to define a `data-imageboss-width` with the max-width of that image, and set the `width` of the image to something that fits your layout. So ImageBoss will generate the image considering the `data-imageboss-width` but you can still display it with the size you need (defining a width attribute or a width on yout CSS).

If you provide a URL or a working Codepen, jsFiddle I could try to support you.

**Comment by verbeeksteven** [comment]
What I ended up doing was changing the width and height to a function like

```
   function getImageWidth(img) {
        if (getAttribute(img, 'width')) {
            return getAttribute(img, 'width');
        }

        if (yieldValidSize(img.getAttribute('width'))) {
            return yieldValidSize(img.getAttribute('width'));
        }

        if (img.clientWidth < 1) {
            return img.clientWidth;
        }

        return img.parentNode.clientWidth;
    }
```

Which adds a final fallback for the parent node size.

Did this for both width and height.

And then changed my sliders from cover to width and set a `data-imageboss-width` to the max-width.

**Comment by igorescobar** [comment]
I'm glad you sorted it out! I noticed that you used this `parentNode.clientWidth` to determine the width of that image. We need to study how we could incorporate this (or similar) without leading to unexpected results to other clients.

**Comment by verbeeksteven** [comment]
I think the `parentNode` width/height can be an easy fallback rather then the "Could not determine image size" since the imageboss size (especially for cover) is save to fallback to the width/height of the parent.

Most css frameworks and css resets (obviously this is not 100% of sites since everything is different) set img to `max-width:100%; height: auto;` which is equal to `parentNode.clientWidth`

But this is completely up in the air, it works for me. But it probably won't work for everything.

**Comment by igorescobar** [comment]
I completely agree with you. it could be incorporated (at least for `data-imageboss-operation="width"`). We just need to run some more tests.

For operations where `height` is need... is where it could go wrong, I think.

I'm more inclined to giving you the flexibility to inject your own behavior rather than trying to come up with a too generic approach and ending up delivering unexpected results. I need to think a bit more about it.

**Comment by igorescobar** [comment]
@verbeeksteven what if:

To globally overwrite the mechanism you could do something like:
```js
window.ImageBoss = {
  ...
  callbacks: {
    resolveWidth: (el) => { /* my logic here*/ },
  }
}
```

And to locally overwrite:

```js
myResolveWidth = (el) => { /* my logic here*/ }
ImageBoss.bindCallback(myImageElement, 'resolveWidth', myResolveWidth);
```

Consider just the interface and not the actual name of the methods etc.

**Comment by verbeeksteven** [comment]
I would prefer something like that to what I am doing.

At the moment I've got two websites hooked up on this with my adjustments stated above and it was mostly painless.

Sliders really give me most of the trouble, I think something that may be a bit easier is it there was a way to do "some" via a callback so.

    <img src="" data-imageboss-src="blah.jpg" data-imageboss-initialize="false">

So turn it off automatically being picked up then something like

    ImageBoss.rebuild();

Or something that would scan all the elements without `data-imageboss-loaded="true"` and "load" them.

There may be a lot of instances where you want to wait for the rest of the content to load before initializing the images.

**Comment by igorescobar** [comment]
@verbeeksteven can you share a link of where are these sliders? 

This library already listens to dynamically added elements. The only problem that I see with this is if your `img` tags have the `data-imageboss-src` but the element isn't "ready" to be used by the library. 

If you have any working example of your setup, would be super helpful.

**Comment by verbeeksteven** [comment]
https://codepen.io/sverbeek/pen/bGGXNxx

This example is slickjs which is an extremely popular jquery slider.

**Comment by igorescobar** [comment]
Thanks a lot for sharing the Codepen!

What I noticed is that... There is no width defined for that image so I just added a CSS rule:
`img { width: 100% }`. And it worked. It's probably better than changing the source code of the library.

Meanwhile, we will work on a improvement for this as possible.

**Comment by igorescobar** [comment]
@verbeeksteven We will keep it simple for now. We added the new handler for the element width. Just upgrade to `2.0.7`.
